#
# Copyright (c) Caiden Sanders and his affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

name: DeployWebFrontendToAWS

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  #
  # deploy: Deploys the WebFrontend to AWS EC2 via SCP
  #
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      # Install Dependencies (from network)
      - name: Install Dependencies (from network)
        run: |
          yarn install --check-files --force
          yarn --cwd packages/frontend install --check-files --force
      
      # Build web-frontend into /build directory and gzipper
      - name: Build Web-Frontend and GZIP
        run: |
          yarn --cwd packages/frontend build

      # Builds TAR in root directory
      - name: Build TAR in Root Directory
        run: |
          mkdir ./build
          cp -TR ./packages/frontend/build/ build

      # Copy file VIA SSH Key to Ubuntu AWS EC2
      - name: Copy file VIA SSH Key to Ubuntu AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "./build/*"
          target: "/srv/www/cloink.net/"
          strip_components: 1
          overwrite: true
      
